server:
  port: 8087 #服务端口
spring:
  application:
    name: app-zuul-gateway #指定服务名


###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
           defaultZone: http://lgh:123456@127.0.0.1:8100/eureka
###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #指定实例id

zuul:
  #prefix: /api   #请求前缀
  #strip-prefix: true  #请求真正服务地址时是否移除前缀，默认是true截取
  routes: #定义服务转发规则
    item-ab: #item-service这个名字任意取的
      path: /item-aabb/** #配置请求URL的请求规则
      #url: http://127.0.0.1:8081 #真正的微服务地址，path匹配的请求都转发到这里
      serviceid: app-item
    #order-cd: #item-service这个名字任意取的
      #path: /order-ccdd/**
      #serviceid: app-order
    app-order: /order-eeff/**
  ignored-services: '*'   #使用'*'可忽略所有微服务
  #ignored-patterns: /**/order/**      #忽略某些指定路径的请求